// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaintingApp.Data;

#nullable disable

namespace PaintingApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205101730_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("PaintingApp.Data.Entities.DrawingBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("DrawingBoards");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCanvasHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(600);

                    b.Property<int>("DefaultCanvasWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(800);

                    b.Property<string>("DefaultStrokeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#000000");

                    b.Property<string>("DefaultStrokeStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Solid");

                    b.Property<double>("DefaultStrokeThickness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.0);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCanvasHeight = 600,
                            DefaultCanvasWidth = 800,
                            DefaultStrokeColor = "#000000",
                            DefaultStrokeStyle = "Solid",
                            DefaultStrokeThickness = 2.0,
                            Description = "Default profile for quick start",
                            Name = "Default User",
                            Theme = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCanvasHeight = 768,
                            DefaultCanvasWidth = 1024,
                            DefaultStrokeColor = "#FFFFFF",
                            DefaultStrokeStyle = "Solid",
                            DefaultStrokeThickness = 3.0,
                            Description = "Profile optimized for dark theme",
                            Name = "Dark Theme User",
                            Theme = "Dark"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCanvasHeight = 1080,
                            DefaultCanvasWidth = 1920,
                            DefaultStrokeColor = "#FF5722",
                            DefaultStrokeStyle = "Solid",
                            DefaultStrokeThickness = 1.5,
                            Description = "Profile for detailed artwork",
                            Name = "Large Canvas User",
                            Theme = "Light"
                        });
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DrawingBoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FillColor")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryData")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrokeStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Solid");

                    b.Property<double>("StrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<int?>("TemplateGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DrawingBoardId");

                    b.HasIndex("TemplateGroupId");

                    b.ToTable("Shapes", t =>
                        {
                            t.HasCheckConstraint("CK_Shape_ParentConstraint", "([DrawingBoardId] IS NOT NULL AND [TemplateGroupId] IS NULL) OR ([DrawingBoardId] IS NULL AND [TemplateGroupId] IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#FFD700",
                            GeometryData = "{\"Points\":[{\"X\":50,\"Y\":0},{\"X\":61,\"Y\":35},{\"X\":98,\"Y\":35},{\"X\":68,\"Y\":57},{\"X\":79,\"Y\":91},{\"X\":50,\"Y\":70},{\"X\":21,\"Y\":91},{\"X\":32,\"Y\":57},{\"X\":2,\"Y\":35},{\"X\":39,\"Y\":35}]}",
                            StrokeColor = "#FFD700",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 1,
                            Type = "Polygon",
                            ZIndex = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#DEB887",
                            GeometryData = "{\"X\":20,\"Y\":50,\"Width\":60,\"Height\":45}",
                            StrokeColor = "#8B4513",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 2,
                            Type = "Rectangle",
                            ZIndex = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#B22222",
                            GeometryData = "{\"Points\":[{\"X\":50,\"Y\":10},{\"X\":85,\"Y\":50},{\"X\":15,\"Y\":50}]}",
                            StrokeColor = "#8B0000",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 2,
                            Type = "Triangle",
                            ZIndex = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#64B5F6",
                            GeometryData = "{\"X\":10,\"Y\":35,\"Width\":50,\"Height\":30}",
                            StrokeColor = "#2196F3",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 3,
                            Type = "Rectangle",
                            ZIndex = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#64B5F6",
                            GeometryData = "{\"Points\":[{\"X\":60,\"Y\":15},{\"X\":95,\"Y\":50},{\"X\":60,\"Y\":85}]}",
                            StrokeColor = "#2196F3",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 3,
                            Type = "Triangle",
                            ZIndex = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#FFEB3B",
                            GeometryData = "{\"CenterX\":50,\"CenterY\":50,\"Radius\":40}",
                            StrokeColor = "#000000",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 4,
                            Type = "Circle",
                            ZIndex = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#000000",
                            GeometryData = "{\"CenterX\":35,\"CenterY\":40,\"Radius\":5}",
                            StrokeColor = "#000000",
                            StrokeStyle = "Solid",
                            StrokeThickness = 1.0,
                            TemplateGroupId = 4,
                            Type = "Circle",
                            ZIndex = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#000000",
                            GeometryData = "{\"CenterX\":65,\"CenterY\":40,\"Radius\":5}",
                            StrokeColor = "#000000",
                            StrokeStyle = "Solid",
                            StrokeThickness = 1.0,
                            TemplateGroupId = 4,
                            Type = "Circle",
                            ZIndex = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GeometryData = "{\"CenterX\":50,\"CenterY\":62,\"RadiusX\":20,\"RadiusY\":10}",
                            StrokeColor = "#000000",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 4,
                            Type = "Oval",
                            ZIndex = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#F48FB1",
                            GeometryData = "{\"CenterX\":25,\"CenterY\":50,\"Radius\":20}",
                            StrokeColor = "#E91E63",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 5,
                            Type = "Circle",
                            ZIndex = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#A5D6A7",
                            GeometryData = "{\"X\":55,\"Y\":30,\"Width\":35,\"Height\":40}",
                            StrokeColor = "#4CAF50",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 5,
                            Type = "Rectangle",
                            ZIndex = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FillColor = "#CE93D8",
                            GeometryData = "{\"Points\":[{\"X\":50,\"Y\":5},{\"X\":70,\"Y\":25},{\"X\":30,\"Y\":25}]}",
                            StrokeColor = "#9C27B0",
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateGroupId = 5,
                            Type = "Triangle",
                            ZIndex = 0
                        });
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.TemplateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("TemplateGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5-pointed star shape",
                            Name = "Star",
                            ProfileId = 1,
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simple house with roof",
                            Name = "House",
                            ProfileId = 1,
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Right-pointing arrow",
                            Name = "Arrow",
                            ProfileId = 2,
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Happy face emoji style",
                            Name = "Smiley Face",
                            ProfileId = 2,
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Collection of basic geometric shapes",
                            Name = "Basic Shapes Set",
                            ProfileId = 3,
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.DrawingBoard", b =>
                {
                    b.HasOne("PaintingApp.Data.Entities.Profile", "Profile")
                        .WithMany("DrawingBoards")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Shape", b =>
                {
                    b.HasOne("PaintingApp.Data.Entities.DrawingBoard", "DrawingBoard")
                        .WithMany("Shapes")
                        .HasForeignKey("DrawingBoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaintingApp.Data.Entities.TemplateGroup", "TemplateGroup")
                        .WithMany("Shapes")
                        .HasForeignKey("TemplateGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DrawingBoard");

                    b.Navigation("TemplateGroup");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.TemplateGroup", b =>
                {
                    b.HasOne("PaintingApp.Data.Entities.Profile", "Profile")
                        .WithMany("TemplateGroups")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.DrawingBoard", b =>
                {
                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Profile", b =>
                {
                    b.Navigation("DrawingBoards");

                    b.Navigation("TemplateGroups");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.TemplateGroup", b =>
                {
                    b.Navigation("Shapes");
                });
#pragma warning restore 612, 618
        }
    }
}
