// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaintingApp.Data;

#nullable disable

namespace PaintingApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205095440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("PaintingApp.Data.Entities.DrawingBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("DrawingBoards");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCanvasHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(600);

                    b.Property<int>("DefaultCanvasWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(800);

                    b.Property<string>("DefaultStrokeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#000000");

                    b.Property<string>("DefaultStrokeStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Solid");

                    b.Property<double>("DefaultStrokeThickness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.0);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DrawingBoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FillColor")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryData")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrokeStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Solid");

                    b.Property<double>("StrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<int?>("TemplateGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DrawingBoardId");

                    b.HasIndex("TemplateGroupId");

                    b.ToTable("Shapes", t =>
                        {
                            t.HasCheckConstraint("CK_Shape_ParentConstraint", "([DrawingBoardId] IS NOT NULL AND [TemplateGroupId] IS NULL) OR ([DrawingBoardId] IS NULL AND [TemplateGroupId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.TemplateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("TemplateGroups");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.DrawingBoard", b =>
                {
                    b.HasOne("PaintingApp.Data.Entities.Profile", "Profile")
                        .WithMany("DrawingBoards")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Shape", b =>
                {
                    b.HasOne("PaintingApp.Data.Entities.DrawingBoard", "DrawingBoard")
                        .WithMany("Shapes")
                        .HasForeignKey("DrawingBoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaintingApp.Data.Entities.TemplateGroup", "TemplateGroup")
                        .WithMany("Shapes")
                        .HasForeignKey("TemplateGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DrawingBoard");

                    b.Navigation("TemplateGroup");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.TemplateGroup", b =>
                {
                    b.HasOne("PaintingApp.Data.Entities.Profile", "Profile")
                        .WithMany("TemplateGroups")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.DrawingBoard", b =>
                {
                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.Profile", b =>
                {
                    b.Navigation("DrawingBoards");

                    b.Navigation("TemplateGroups");
                });

            modelBuilder.Entity("PaintingApp.Data.Entities.TemplateGroup", b =>
                {
                    b.Navigation("Shapes");
                });
#pragma warning restore 612, 618
        }
    }
}
